/** Autogenerated Main.cpp. */

// ======================| Include only the DSP files  |======================

#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ================| Now we can add the rest of the codebase |================

#include <JuceHeader.h>

// ============================| Project Factory |============================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ------------------------------------------------
		
		registerNode<project::sidechain_comp>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

